### ISSUE TITLE
需要10.15以上？

### ISSUE THREAD

**Issue by hongzhixiong** [rhinoc/trans#1]
10.14没法用吖，再就是加上有道翻译的API吧

**Comment by rhinoc** [comment]
deployment target 之前设置的是10.15，改成10.14就行了
现在release的v1.3.1支持10.14了
下一个版本会加上有道翻译API的支持和设置自己的Token

**Comment by hongzhixiong** [comment]
> deployment target 之前设置的是10.15，改成10.14就行了
> 现在release的v1.3.1支持10.14了
> 下一个版本会加上有道翻译API的支持和设置自己的Token

谢谢开发。希望可以支持长句翻译完整显示，现有的显示框容量比较有限。

**Comment by rhinoc** [comment]
有道翻译api已添加。

关于长句翻译完整显示，目前不在计划中，因为如果是复制显示通知的话肯定是显示不全的，如果是在popover内显示需要popover尺寸的自适应，那每次翻译的时候popover的尺寸都会改变。

此外，有道翻译的api限制20字符，长句基本是不可能的啦。需要长句翻译的话可以切换到百度翻译，然后在popover或通知中copy，一种权宜之计。

感谢关注，新年快乐。
