### ISSUE TITLE
readMe建议

### ISSUE THREAD

**Issue by tianzhipengfei** [rhinoc/trans#6]
老哥，我提个建议，你要提那个小翻译提供灵感的话，你提一下就好了，你放了一个别人的截图不放自己的，我就去下了别人的了，然后感觉效果不好，准备回来看看你这怎么介绍自己的，才发现，你写的不是小翻译……

**Comment by rhinoc** [comment]
建议已采纳，把图片删了换成了itunes链接，谢谢支持～
